steps:
  # Create .env file from Cloud Build substitution variables
  - name: "bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cat <<EOF > .env
        APP_NAME=${_APP_NAME}
        APP_ENV=${_APP_ENV}
        APP_KEY=${_APP_KEY}
        APP_DEBUG=${_APP_DEBUG}
        APP_URL=${_APP_URL}
        DB_CONNECTION=${_DB_CONNECTION}
        WEATHER_API_KEY=${_WEATHER_API_KEY}
        WEATHER_API_ENDPOINT=${_WEATHER_API_ENDPOINT}
        EOF

  # Remove any trailing whitespace and empty lines
  - name: "bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed -i 's/[[:space:]]*$//' .env
        sed -i '/^$/d' .env

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "9804"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
